version: '3.8'
services:
  postgres-auth:
    image: postgres:14
    container_name: postgres-inventory

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    command: ["postgres", "-c", "port=5435"]

    ports:
      - '5435:5435'
    volumes:
      - postgres-inventory-data:/var/lib/postgresql/data

volumes:
  postgres-inventory-data:
