version: '3.8'
services:
  postgres-auth:
    image: postgres:14
    container_name: postgres-item-catalog

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    command: ["postgres", "-c", "port=5433"]

    ports:
      - '5433:5433'
    volumes:
      - postgres-item-catalog-data:/var/lib/postgresql/data

volumes:
  postgres-item-catalog-data:
