version: "3.8"
services:
  redis:
    image: redis:7
    container_name: system-redis
    command: redis-server --requirepass mysecurepassword
    networks:
      - system-network
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: system-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - system-network

networks:
  system-network:
    external: true
