version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    env_file:
      - .env
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms${ELASTICSEARCH_HEAP} -Xmx${ELASTICSEARCH_HEAP}
    ports:
      - '${ELASTICSEARCH_HTTP_PORT}:9200'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    env_file:
      - .env
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:${ELASTICSEARCH_HTTP_PORT}
    ports:
      - '${KIBANA_PORT}:5601'
